### ISSUE TITLE
Article metadata block 

### ISSUE THREAD

**Issue by lmullen** [chnm/crdh#4]
[Here is an example article](https://github.com/chnm/crdh-jekyll/blob/add-articles/_essays/v01-02-digitally-analyzing-the-uneven-ground.md) from the first issue with complete metadata.

The article metadata at the top of the article pages should probably display all of the relevant metadata. Here are the items to discuss.

- [x] If an author has a URL, link to it from the author's name
- [x] Include author affiliation
- [x] Include author e-mail
- [x] Include author's ORCID. The format [here](https://cran.rstudio.com/web/packages/rplos/) (look for the author Chamberlain) is standard, I think.
- [x] For the volume identifier: Should it say, `from volume 1`, `from 2018`, `from volume 1 (2018)` or something like that?
- [x] Include a sample citation. Proposed format:

Joshua Catalano, "Digitally Analyzing the Uneven Ground: Language Borrowing Among Indian Treaties," *Current Research in Digital History* 1 (2018): <https://doi.org/whateverthedoiis>.

**Comment by kimisgold** [comment]
@lmullen I think I've completed the checklist. Feel free to review and close if everything looks okay to you.

**Comment by lmullen** [comment]
@kimisgold This looks great. I made a minor change to the liquid logic for the author bios (in the commit linked above) to put a semicolon between multiple authors, and to fix a space between the commas. Closing this issue.
