### ISSUE TITLE
Suggested changes to styling of articles

### ISSUE THREAD

**Issue by lmullen** [chnm/crdh#5]
Some suggested changes to the styling of the articles:

- [x] Block quotations without a left border.
- [x] Decrease the margin between list items in unordered lists and check the vertical rhythm of the lists.
- [x] The spacing between entries in the bibliography also seem too large.
- [x] The headings for the section breaks in the articles (see Catalano article for an example) seem too big to me. Currently they are `<h3>` tags. Should either the `<h3>` font size be smaller, or should we put them into the articles `<h4>`s?
- [x] Figures and figure captions should be stylized. These have been added with a Jekyll plugin. Should we put the figure number directly into the caption? Or should the figures be numbered automatically in CSS using counters?

**Comment by gswain2** [comment]
- [ ] Ability to merge cells in a markdown table so that text in one column (excluding header) can take up the space equal to all of the rows in a table

**Comment by lmullen** [comment]
My guess re the tables is that the most straightforward thing to do is to mark them up as HTML rather than markdown, and use the `rowspan` and `colspan` attributes to format things the way that Guldi and Williams want. We may be able to convert their tables directly to HTML using Pandoc.

**Comment by kimisgold** [comment]
@lmullen Could you look over these latest styles changes to see if they feel any better? Everything in your list should be addressed, but I didn't want to check off anything before you took a look.

**Comment by lmullen** [comment]
Thanks for working on this, @kimisgold. Here are some further thoughts. The lists, bibliography, and so on that I checked off look great. 

- The block quotations look too much like display elements and not like the running text. The block quotation at the top of the Catalano piece looks great, but that one is an epigraph. The block quotations embedded in the text should (I think) be set very simply, perhaps mostly the same as the body text including color and size but with an indented left margin and (as you see fit) perhaps an indented right margin and decreased leading. 

- Likewise I think the figure captions look good for ones that are one or two lines, like in the Howard piece. But for the longer ones, which can be paragraph length (e.g., in Bond there is one which is sixteen lines) they seem too heavy. Is there some way to make the longer captions look less heavy? 

- What would you think about giving the figures and captions a bigger top and bottom margin, so there is more room between them and the surrounding text?

I hope these suggestions are helpful.

**Comment by lmullen** [comment]
@kimisgold Based on what you've done with these figure captions, my assumption is that we should just number them in the markup rather than relying on CSS to number them automatically. Is that your preference?

**Comment by kimisgold** [comment]
@lmullen I've just pushed some style changes that address your most recent points. Can you pull and review?

**Comment by lmullen** [comment]
@kimisgold I love what you did with the figure captions. They look fantastic.

I think everything here is done, so I'll close this issue. Thanks.
