### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lmullen** [chnm/crdh#6]
- [ ] Add the new ISSN number: `ISSN 2637-5923`
- [ ] Replace the placeholder with the RRCHNM logo
- [ ] Include text in the footer about the publication and a donation link.

@srob4757: Could you please draft the text for the footer, perhaps using what we currently have at http://crdh.rrchnm.org as a base?

**Comment by srob4757** [comment]
I think since there is also an about page we can simplify the text: "Current Research in Digital History is published by RRCHNM at George Mason University and funded by donations to the RRCHNM Director’s Fund."
Also:
- [ ] Add the CC License
- [ ] Add the GMU logo

**Comment by lmullen** [comment]
CC-BY-NC-ND

Link here: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode

**Comment by lmullen** [comment]
@kimisgold Two questions about the footer:

1. For the license, could we remove the image and just use the text `This journal is licensed <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND.</a>` ? I think it might look cleaner without that boilerplate, but if you think the text looks fine as it is, then we can leave it.

2. On smaller screen resolutions, the logos and text are flush left against the browser window. Is that your intention?
