### ISSUE TITLE
Home page and cover art

### ISSUE THREAD

**Issue by lmullen** [chnm/crdh#9]
The home page will need some revisions to include the content from 2018

- [x] Site title should be "Current Research in Digital History"
- [x] Past volumes in sidebar and header should include only the ones in the repository.
- [x] Perhaps change the wording `Past volumes` to `all volumes`. Remove the `Archive` title.
- [x] Past volumes need to be linked.
- [x] Cover art for 2018.

**Comment by kimisgold** [comment]
A note regarding the appearance of past volumes: I think this has already been addressed, but the site is showing placeholder volumes because there are are placeholder essays that reference those volumes.

**Comment by lmullen** [comment]
Ah. I didn't realize those back issues were appearing for that reason. We will clear out the placeholder articles, which is #3.
